#!/usr/bin/env bash

lf() {
    local cmd='nnn -dHiU'

    local prefix=''
    # stdout is a tty, TMUX is not empty (we're in tmux)
    if [[ -t 1 && -n $TMUX ]] && command -v tmux &>/dev/null; then
        prefix='tmux display-popup -E -w 75% -h 75%'
    fi

    $prefix $cmd "$(pwd)"
}
