#!/usr/bin/env bash

lp() {
    eza \
        --icons=always \
        --all \
        --long \
        --group-directories-last \
        --binary \
        --smart-group \
        --octal-permissions \
        --no-time \
        --color=always \
        "${1:-.}" \
        | fzf --ansi
}
